import type { Metadata } from 'next';
// import { Time } from "next/font/google";
import './globals.css';

// const timesNewRoman =

export const metadata: Metadata = {
	title: 'Samriddh Pratap Verma - Resume',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased`}>{children}</body>
		</html>
	);
}
