import type { Metadata } from "next";
// import { Time } from "next/font/google";
import "./globals.css";
import Resume from "./components/Resume";

// const timesNewRoman =

export const metadata: Metadata = {
  title: `${Resume.header.name} - Resume`,
  description:
    "Generated by Resume Builder made by https://github.com/SamriddhVermaSRM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
